services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app_network
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  app:
    container_name: async_app
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    networks:
      - app_network
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_VERSION=0.0.1
      - DOCS_URL=${DOCS_URL?Variable not set}
      - OPENAPI_URL=${OPENAPI_URL?Variable not set}
      - REDOC_URL=${REDOC_URL?Variable not set}
      - SERVER_HOST=${SERVER_HOST?Variable not set}
      - SERVER_PORT=8000
      - SERVER_WORKERS=4
      - SCHEME=asyncpg
      - DB=postgresql+asyncpg://admin:changethis@db:5432/load
      - POSTGRES_POOL_SIZE=${POSTGRES_POOL_SIZE?Variable not set}

  psycopg2:
    container_name: psycopg2_app
    build:
      dockerfile: Dockerfile-psycopg2
      context: ./
    restart: always
    networks:
      - app_network
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_VERSION=0.0.1
      - DOCS_URL=${DOCS_URL?Variable not set}
      - OPENAPI_URL=${OPENAPI_URL?Variable not set}
      - REDOC_URL=${REDOC_URL?Variable not set}
      - SERVER_HOST=${SERVER_HOST?Variable not set}
      - SERVER_PORT=8000
      - SERVER_WORKERS=4
      - SCHEME=asyncpg
      - DB=postgresql+psycopg2://admin:changethis@db:5432/load
      - POSTGRES_POOL_SIZE=${POSTGRES_POOL_SIZE?Variable not set}

  psycopg3:
    container_name: psycopg3_app
    build:
      dockerfile: Dockerfile-psycopg3
      context: ./
    restart: always
    networks:
      - app_network
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_VERSION=0.0.1
      - DOCS_URL=${DOCS_URL?Variable not set}
      - OPENAPI_URL=${OPENAPI_URL?Variable not set}
      - REDOC_URL=${REDOC_URL?Variable not set}
      - SERVER_HOST=${SERVER_HOST?Variable not set}
      - SERVER_PORT=8000
      - SERVER_WORKERS=4
      - SCHEME=asyncpg
      - DB=postgresql+psycopg://admin:changethis@db:5432/load
      - POSTGRES_POOL_SIZE=${POSTGRES_POOL_SIZE?Variable not set}

networks:
  app_network:
